apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: host-machine-role
rules:
  - apiGroups: [""]
    resources:
      [
        "namespaces",
        "configmaps",
        "events",
        "replicationcontrollers",
        "serviceaccounts",
        "pods/logs",
      ]
    verbs: ["get", "list", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "statefulsets"]
    verbs: ["list"]
  - apiGroups: ["extensions", "apps", "networking.k8s.io"]
    resources: ["deployments", "replicasets", "ingresses"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: [""]
    resources: ["services/proxy", "pods/portforward"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: host-machine-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: host-machine-role
subjects:
  - namespace: default
    kind: ServiceAccount
    name: host-machine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: host-machine
